llama2-7b:
  hf_key: "NousResearch/Llama-2-7b-chat-hf"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
  # ft_model_path: "locuslab/tofu_ft_llama2-7b" #this model will be used for unlearning by default
  ft_model_path: "data/ft_epoch5_lr1e-05_llama2-7b_full_wd0.01/checkpoint-625" #this model will be used for unlearning by default
  hp_ft_retain_model_path: "models/hp-llama2-7b/checkpoint-4410"
  harm_model_path: meta-llama/Llama-2-7b-hf"
llama3.1:
  hf_key: "meta-llama/Meta-Llama-3.1-8B"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
  # ft_model_path: "locuslab/tofu_ft_llama2-7b" #this model will be used for unlearning by default
  # hp_ft_retain_model_path: "models/hp-llama2-7b/checkpoint-4410"
  harm_model_path: "meta-llama/Meta-Llama-3.1-8B"
phi:
  hf_key: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  # ft_model_path: "locuslab/tofu_ft_phi-1.5"
  ft_model_path: "/home/azureuser/cloudfiles/code/Users/yaxuan.wang/baseline/tofu/data/ft_epoch5_lr2e-05_phi_full_wd0.01/checkpoint-625"
stablelm:
  hf_key: "stabilityai/stablelm-3b-4e1t"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ft_model_path: "paper_models/final_ft_noLORA_5_epochs_inst_lr1e-05_stablelm/checkpoint-625"
pythia-1.4:
  hf_key: "EleutherAI/pythia-1.4b-deduped"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
opt-1.3b:
  hf_key: "facebook/opt-1.3b"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ft_model_path: "data/ft_epoch5_lr2e-05_opt-1.3b_full_wd0.01/checkpoint-625"
opt-2.7b:
  hf_key: "facebook/opt-2.7b"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ft_model_path: "data/ft_epoch5_lr2e-05_opt-2.7b_full_wd0.01/checkpoint-625"
  hp_ft_retain_model_path: "models/hp_opt-2.7b/checkpoint-4410"
mixtral:
  hf_key: "mistralai/Mixtral-8x7B-Instruct-v0.1"
zephyr:
  hf_key: "HuggingFaceH4/zephyr-7b-beta"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"